remote_theme: pages-themes/primer
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [<a href="Home.md"><img align="left" width="80" height="80" src="logo_Z4D.png" alt="Logo"></a> ZigBeeForDomoticZ plugin Wiki]
description: []
